### ISSUE TITLE
Spanning tree error

### ISSUE THREAD

**Issue by phil-dileo** [arista-eosplus/ansible-eos-mlag#6]
Data

```
mlag:
    mlag_domain_id: mlag1
    mlag_trunk_group: mlagpeer
    mlag_shutdown: false
    local_if_vlan: Vlan1024
    local_if_ip_address: 10.0.0.1/30
    local_if_disable_spanning_tree: true
    peer_address: 10.0.0.2
    peer_link_if: Port-Channel10
    peer_link_mode: trunk
    peer_link_lacp_mode: active
    peer_link_enable: true
    peer_link_members:
      - Ethernet3
      - Ethernet4
```

Error:

```
TASK [arista.eos-mlag : Arista MLAG (Base Configuration)] **********************
fatal: [dc1-tora]: FAILED! => {"changed": false, "code": 1002, "commands": ["configure terminal", "vlan 1024", "name MLAG-PEERING", "trunk group mlagpeer", "state active", "interface Port-Channel10", "switchport mode trunk", "switchport trunk group mlagpeer", "no spanning-tree vlan 1024", "mlag configuration", "local-interface Vlan1024", "peer-address 10.0.0.2", "peer-link Port-Channel10", "domain-id mlag1", "interface Vlan1024", "description mlag1", "ip address 10.0.0.1/30"], "data": [{}, {}, {}, {}, {}, {}, {}, {}, {}, {"errors": ["incomplete command (at token 4: None)"]}], "failed": true, "message": "CLI command 10 of 18 'no spanning-tree vlan 1024' failed: invalid command", "msg": "json-rpc error"}
```
